version: "3.9"

services:
  reg_s:
    #environment:
    #- REGISTRATION_PORT=${REGISTRATION_PORT}
    #- LISTENING_PORT=${SEQUENCER_PORT}
    #- PEER_PORT=${MULTICAST_PORT}
    container_name: registry
    hostname: registry
    build:
      context: .
      dockerfile: ./docker/Dockerfile_registration
    env_file: .env
    networks:
      - mapreduce
      #ports:
      #- ${SEQUENCER_PORT}

  master_s:
    #environment:
      #- REGISTRATION_PORT=${REGISTRATION_PORT}
      #- LISTENING_PORT=${SEQUENCER_PORT}
      #- PEER_PORT=${MULTICAST_PORT}
    container_name: master
    hostname: master
    build:
      context: .
      dockerfile: ./docker/Dockerfile_master
    env_file: .env
    networks:
      - mapreduce
    #ports:
     #- ${SEQUENCER_PORT}

  worker_s:
    #environment:
      #- MEMBERS_NUM=${MEMBERS_NUM}
      #- REGISTRATION_PORT=${REGISTRATION_PORT}
      #- MULTICAST_PORT=${MULTICAST_PORT}
      #- SEQUENCER_PORT=${SEQUENCER_PORT}
      #- CONTROL_PORT=${CONTROL_PORT}
    build:
      context: .
      dockerfile: ./docker/Dockerfile_worker
    env_file: .env
    #ports:
      #- ${MULTICAST_PORT}
      #- ${CONTROL_PORT}
    networks:
      - mapreduce

networks:
  mapreduce:
    driver: bridge