version: "3.9"

services:
  reg_s:
    container_name: registry
    hostname: registry
    build:
      context: .
      dockerfile: docker/Dockerfile_registration
    env_file: .env
    networks:
      - mapreduce
    volumes:
      - ./doc:/doc

  master_s:
    container_name: master
    hostname: master
    build:
      context: .
      dockerfile: docker/Dockerfile_master
    env_file: .env
    networks:
      - mapreduce
    depends_on:
      - reg_s
      - worker_s
    volumes:
      - ./doc:/doc

  worker_s:
    build:
      context: .
      dockerfile: docker/Dockerfile_worker
    env_file: .env
    networks:
      - mapreduce
    depends_on:
      - reg_s
    volumes:
      - ./doc:/doc

networks:
  mapreduce:
    driver: bridge