version: "3.9"

services:
  master_s:
    container_name: master
    hostname: master
    build:
      context: ./Master
      dockerfile: Dockerfile
    env_file: .env
    ##networks:
      ##- mutual_exclusion_network
    volumes:
      - ./logs:/logs

  worker_s:
    deploy:
      replicas: 3
    build:
      context: ./Worker
      dockerfile: Dockerfile
    env_file: .env
    ##networks:
      ##- mutual_exclusion_network
    volumes:
      - ./logs:/logs