# syntax=docker/dockerfile:1
FROM golang:1.17-alpine
ADD . /code/master-worker/registry
WORKDIR /code/master-worker/registry
COPY . .
#RUN go mod download
RUN go build -o ./main ./code/master-worker/registry
ENTRYPOINT ["./main"]